### ISSUE TITLE
Feature: Trace actual dependencies.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/serverless-jetpack#48]
Like webpack, just parse the entry points and get a list of files actually required, then glob them specifically and exclude everything else...

- Probably use a straight parser (maybe what webpack uses?)
- Note limitations / drawbacks / etc (e.g., no dynamic requires)

Possible references / research:

- https://github.com/zeit/node-file-trace
- https://github.com/depcheck/depcheck

**Comment by nikita-lipnyagov** [comment]
**Dear colleagues**, could you, please, provide some detailed info whether this feature will be implemented and approximate timelines, if it wiil?

Thank you for attention, you are making cool product!

**Comment by ryan-roemer** [comment]
Feature released in `serverless-jetpack@0.10.0`

See the tracing guide at https://github.com/FormidableLabs/serverless-jetpack#experimental-tracing-mode to integrate and use and would ❤️ to hear how it goes for folks packaging! (Speed, size, and correctness given all the caveats)
